### ISSUE TITLE
Should attempt to cast value to number

### ISSUE THREAD

**Issue by w33ble** [elastic/tinymath#24]
When given an array of string, or even a simple string, tinymath should probably try to cast to a `Number` type first before returning a `NaN`. 

This line should probably use `isNaN(Number(arg))`: https://github.com/elastic/tinymath/blob/master/src/index.js#L65

**Comment by cqliu1** [comment]
@rashidkpc and I talked about this, and we decided a better place to fix this is in `esdocs` in Canvas. TinyMath should only handle numbers for now.
