### ISSUE TITLE
Evaluate doesn't throw error when overwriting existing functions

### ISSUE THREAD

**Issue by tsullivan** [elastic/tinymath#25]
There need to be some reserved words that the `evaluate` function will break with. 

Example is, I can override the built-in `add` function to do whatever I want:
```
> const { evaluate } = require('tinymath');
undefined
> evaluate('add(num1, num2)', { num1: 1, num2: 7 }, { add: function(num1, num2) { return num1 / num2; } });
0.14285714285714285
```

Here's another example that just runs an expression:
```
> evaluate('num1 + num2', { num1: 1, num2: 7 }, { add: function(num1, num2) { return num1 == num2; } });
false
```

**Comment by cqliu1** [comment]
This actually isn't an issue. Per @rashidkpc we want to allow the user to override built-in functions with custom logic to fit their needs. For example, the user may want to change `add` to handle string concatenation (which it currently does not.)
